### ISSUE TITLE
Where to find lighting pattern gt

### ISSUE THREAD

**Issue by spock-the-wizard** [oppo-us-research/OpenIlluminationCapture#2]
Hi, thank you for the great dataset.

I'm trying to use the light pattern dataset, and am having trouble finding the lighting gt for each pattern.
(e.g. envmap? individual point lights)

thanks in advance!

**Comment by spock-the-wizard** [comment]
Also do you provide how to transform the cameras in light-pattern setting to OLAT setting? That would be super useful!

**Comment by ootts** [comment]
Hi, thanks for using our dataset. For the second question, refer to [here](https://huggingface.co/datasets/OpenIllumination/OpenIllumination/blob/main/others/joint_calib/greenhead/README.md).

**Comment by yehonathanlitman** [comment]
Bump, how do we get the lighting pattern? generate_light_gt_sg.py uses data that we don't have access to but it also doesn't generate an envmap. Could you provide us with a google drive link to the envmaps or provide instructions on how to generate them?

**Comment by Isabella98Liu** [comment]
> Bump, how do we get the lighting pattern? generate_light_gt_sg.py uses data that we don't have access to but it also doesn't generate an envmap. Could you provide us with a google drive link to the envmaps or provide instructions on how to generate them?

Thank you for expressing your interest in our dataset. Regarding the environment map of the lights per OLAT, we provide SG parameters of each light in our paper, which are 236.97054 for lobe size, 5 for light intensity, and the light positions are available in [light_pos.npy](https://huggingface.co/datasets/OpenIllumination/OpenIllumination/blob/main/light_pos.npy) You can use these parameters to construct each light's SG function and convert it into environment map accordingly ([reference](https://github.com/Kai-46/PhySG/blob/030d590bc007377007c65046c8f70ad149cfb371/code/envmaps/fit_envmap_with_sg.py#L24)). All the light positions and camera poses are aligned in the world coordinate ([more information can be found at this link](https://huggingface.co/datasets/OpenIllumination/OpenIllumination/blob/main/others/joint_calib/greenhead/README.md)).

Should you have any questions or need further assistance in using our dataset, please don't hesitate to reach out. We appreciate your interest in our work. :)

**Comment by Isabella98Liu** [comment]
@yehonathanlitman Hi Yehonathan! for your convenience, we provide the 13 GT light patterns used in our paper in HDR and SG formats [here](https://drive.google.com/file/d/1BPcmdoFESLzwSaC-76CX1sPEKBGekdr0/view?usp=sharing).

**Comment by yehonathanlitman** [comment]
Thank you for the PhySG script and envmaps! All the best
