### ISSUE TITLE
Parameters to run experiments.

### ISSUE THREAD

**Issue by prk9009** [oppo-us-research/OpenIlluminationCapture#3]
Hi, I wanted to know what hyperparameters are used to run methods like TensoIR and PhySG, when I run these methods I get significantly lower PSNR values and the reconstruction has a lot of floating artifacts.

Thanks.
![079999_000](https://github.com/oppo-us-research/OpenIlluminationCapture/assets/21962358/5f961d42-9ca3-433e-af3c-e2760182c08a)

**Comment by Isabella98Liu** [comment]
Hello, we appreciate your use of our dataset! For `TensoIR`, you can access the configuration file [here](https://github.com/oppo-us-research/OpenIlluminationCapture/blob/main/third_party/TensoIR/configs/singleillum.txt), and detailed instructions are available [here](https://github.com/oppo-us-research/OpenIlluminationCapture/blob/main/third_party/TensoIR/README.md). For `PhySG`, please refer to the instructions provided [here](https://github.com/oppo-us-research/OpenIlluminationCapture/blob/main/third_party/PhySG/README.md). It appears that the issues you're encountering may be related to inaccurate camera parameters, please ensure that you load the cameras correctly, your can refer to the dataloader we provide in our repository under `third-party` folder. Should you encounter any difficulties with the dataset, please don't hesitate to reach out for assistance.
